src/crm/api/v1/company/urls.py
from django.urls import path
from .student.views import StudentView, ExpectedStudentView
from .profile.views import ProfileView
from .position.views import PositionView
from .teacher.views import TeacherView


urlpatterns = [
    path('teacher/<int:pk>/', TeacherView.as_view(), name='education_student_one'),
    path('teachers/', TeacherView.as_view(), name='education_student_one'),
    path('students/<int:pk>/', StudentView.as_view(), name='education_student_one'),
    path('students/', StudentView.as_view(), name='education_student_list'),
    path('expected_students/', ExpectedStudentView.as_view(), name='expected_students_list'),
    path('expected_student/<int:pk>/', ExpectedStudentView.as_view(), name='expected_student'),
    path('profile/', ProfileView.as_view(), name='education_profile_one'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='education_profile_edit'),
    path('position/<int:pk>/', PositionView.as_view(), name='education_position_one'),
    path('position/', PositionView.as_view(), name='education_position_one'),

]

src/crm/dashboard/company/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("profile/", views.company_profile, name="company-profile"),
    path("edit/", views.company_edit, name="company-edit"),
    path("positions/", views.position_list, name="position-list"),
    path('positions/<int:pk>/info/', views.position_details, name='position-details'),
    path('positions/<int:pk>/edit/', views.position_edit, name='position-edit'),
    path('positions/<int:pk>/delete/', views.position_delete, name='position-delete'),
    path('positions/add/', views.position_create, name='position-add'),
    path("employees/", views.employee_list, name="employee-list"),
    path('employees/<int:pk>/info/', views.employee_details, name='employee-details'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee-edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee-delete'),
    path('employees/add/', views.employee_create, name='employee-add'),
]

src/crm/dashboard/urls.py
from . import views as core_views
from django.urls import path, include
app_name = 'dashboard'
urlpatterns = [
        path('', core_views.index, name='dashboard_index'),
        path('dashboard/', core_views.index, name='dashboard_index'),
        path('login/', core_views.login, name='login'),
        path('logout/', core_views.logout, name='logout'),
        path('company/', include('crm.dashboard.company.urls')),
        path('education/', include('crm.dashboard.education.urls')),
        path('timesheet/', include('crm.dashboard.timesheet.urls')),
        path('students/', include('crm.dashboard.students.urls')),
        path('monitoring/', include('crm.dashboard.monitoring.urls')),
]

src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from .api.v1.urls import urlpatterns as v1_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include((v1_urls, 'api-v1'), namespace='api-v1')),
    path('', include('crm.dashboard.urls')),
]

src/crm/api/v1/company/position/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound
from .services import list_positions, one_position
from .serializers import PositionSerializer
from crm.company.models import Position


class PositionView(GenericAPIView):

    permission_classes = (AllowAny,)
    serializer_class = PositionSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Position.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found position')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_position(request, kwargs['pk'])
        else:
            result = list_positions(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_position(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        position = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=position, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_position(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        position = self.get_object(*args, **kwargs)
        position.status = 3
        position.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/company/profile/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound
from .services import see_profile
from .serializers import ProfileSerializer
from crm.company.models import Profile


class ProfileView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = ProfileSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Profile.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found profile')
        return product

    def get(self, request, *args, **kwargs):
        result = see_profile()
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = see_profile()
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        profile = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=profile, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = see_profile()
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/api/v1/company/student/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound
from .services import list_students, one_students, expected_student_course, expected_students
from .serializers import StudentSerializer
from crm.company.models import Member

class StudentView(GenericAPIView):

    permission_classes = (AllowAny,)
    serializer_class = StudentSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Member.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found student')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_students(request, kwargs['pk'])
        else:
            result = list_students(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_students(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        student = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=student, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_students(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        student = self.get_object(*args, **kwargs)
        student.status = 3
        student.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)




class ExpectedStudentView(GenericAPIView):

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = expected_student_course(request, kwargs['pk'])
        else:
            result = expected_students(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/api/v1/company/teacher/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound
from .services import teacher_data, list_teachers
from .serializers import TeacherSerializer
from crm.company.models import Member

class TeacherView(GenericAPIView):

    permission_classes = (AllowAny,)
    serializer_class = TeacherSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Member.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found teacher')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = teacher_data(request, kwargs['pk'])
        else:
            result = list_teachers(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/company/views.py
from django.shortcuts import render

# Create your views here.

src/crm/dashboard/company/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from ...base.utils import sql_paginator_items
from crm.company.models import (Position, Profile, Member)
from ..views import staff_member_required
from .forms import (PositionForm, ProfileForm, EmployeeForm, StudentForm)

from .services import (list_position, list_employee,)


@staff_member_required
def company_edit(request):
    try:
        company_model = Profile.objects.order_by('id')[0:1].get()
    except Exception:
        company_model = None

    form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=company_model
    )

    if form.is_valid():
        company_model = form.save()
        return redirect("dashboard:company-profile")


    ctx = {
        "form": form,
        "company_model": company_model,
        "section": 'company',
        "active":"4",
    }
    return TemplateResponse(request, "dashboard/company/profile/form.html", ctx)

@staff_member_required
def company_profile(request):
    pk=request.user.company_id
    try:
        company_model = get_object_or_404(Profile, pk=pk)
    except Exception:
        company_model = None

    ctx = {
        "company_model": company_model,
        "section": 'company',
        "active": "4",
    }
    return TemplateResponse(request, "dashboard/company/profile/detail.html", ctx)


@staff_member_required
def position_list(request):
    pk=request.user.company_id
    positions = list_position(request, pk)
    list = sql_paginator_items(
        positions['items'], positions['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "positions": positions['items'],
        "list": list,
        "section": 'company',
        "active": "5",
    }
    return TemplateResponse(request, "dashboard/company/position/list.html", ctx)


@staff_member_required
def position_create(request):
    pk=request.user.company_id
    company = Profile.objects.get(pk=pk)
    position = Position()
    form = PositionForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        position = form.save()
        return redirect("dashboard:position-list")
    ctx = {"position": position, "form": form, "active":"5","section":"company"}
    print(form.errors)
    return TemplateResponse(request, "dashboard/company/position/form.html", ctx)


@staff_member_required
def position_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = get_object_or_404(Position, pk=pk)
    form = PositionForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=position
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:position-list")
    elif form.errors:
        status = 400
    ctx = {"position": position, "form": form,"section":"company","active":"5"}
    template = "dashboard/company/position/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def position_details(request, pk):
    position = get_object_or_404(Position, pk=pk)
    ctx = {
        "position": position,
        "active": "5",
        "section":"company",
    }
    return TemplateResponse(request, "dashboard/company/position/detail.html", ctx)


@staff_member_required
def position_delete(request, pk):
    position = get_object_or_404(Position, pk=pk)
    position.delete()
    return redirect("dashboard:position-list")


@staff_member_required
def employee_list(request):
    pk=request.user.company_id
    employees = list_employee(request, pk)
    list = sql_paginator_items(
        employees['items'], employees['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "employees": employees['items'],
        "list": list,
        "section": 'company',
        "active": "6",
    }
    return TemplateResponse(request, "dashboard/company/employee/list.html", ctx)

@staff_member_required
def employee_create(request):
    employee = Member()
    pk = request.user.company_id
    company = Profile.objects.get(pk=pk)
    position=Position.objects.filter(company_id=pk)
    form = EmployeeForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    print(form.errors)
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    return TemplateResponse(request, "dashboard/company/employee/form.html", ctx)

@staff_member_required
def employee_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = Position.objects.filter(company_id=company_id)
    employee = get_object_or_404(Member, pk=pk)
    form = EmployeeForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=employee
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    elif form.errors:
        status = 400
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    template = "dashboard/company/employee/form.html"
    return TemplateResponse(request, template, ctx, status=status)

@staff_member_required
def employee_details(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    ctx = {
        "employee": employee,
        "active": "6",
        "section": "company",
    }
    return TemplateResponse(request, "dashboard/company/employee/detail.html", ctx)

@staff_member_required
def employee_delete(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    employee.delete()
    return redirect("dashboard:employee-list")

src/templates/dashboard/company/employee/detail.html
{% extends "dashboard/base.html" %}
{% block title %}
  Hodim - {{ employee.firstname}} {{ block.super }}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block head_title %}Hodim - {{ employee.firstname}}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2">
        <a href="{% url 'dashboard:employee-list' %}" class="fc-prev-button btn btn-primary"> Hodimlar</a>
    </div>
</div>
<div class="row">
     <div class="col-md-12">
         <div class="card">
             <div class="card-body p-0">

                  <div class="responsive-table-plugin">
                           <table class="table table-striped mb-0">
                               <tbody>
                               <tr>
                                   <th>ID</th>
                                   <td>{{ employee.id }}</td>
                               </tr>
                               <tr>
                                   <th>Ism</th>
                                   <td>{{ employee.firstname }}</td>
                               </tr>
                               <tr>
                                   <th>Familiya</th>
                                   <td>{{ employee.lastname }}</td>
                               </tr>
                               <tr>
                                   <th>Otasini ismi</th>
                                   <td>{{ employee.middlename }}</td>
                               </tr>
                               <tr>
                                   <th>Jinsi</th>
                                   <td>
                                       {% if employee.gender == True %}
                                       Erkak
                                       {% else %}
                                       Ayol
                                       {% endif %}
                                   </td>
                               </tr>
                               <tr>
                                   <th>Passport</th>
                                   <td>{{ employee.pass_serial }}</td>
                               </tr>
                               <tr>
                                   <th>Tug‘ilgan kun</th>
                                   <td>{{ employee.birthday }}</td>
                               </tr>
                               <tr>
                                   <th>Viloyat/shahar</th>
                                   <td>{{ employee.region }}</td>
                               </tr>
                               <tr>
                                   <th>Tuman</th>
                                   <td>{{ employee.district }}</td>
                               </tr>
                               <tr>
                                   <th>Manzil</th>
                                   <td>{{ employee.address }}</td>
                               </tr>
                               <tr>
                                   <th>Lavozim</th>
                                   <td>{{ employee.position }}</td>
                               </tr>
                               <tr>
                                   <th>Telefon raqam</th>
                                   <td>{{ employee.phone_number }}</td>
                               </tr>
                               <tr>
                                   <th>Email</th>
                                   <td>{{ employee.email }}</td>
                               </tr>
                               <tr>
                                   <th>Ishga kelgan vaqt</th>
                                   <td>{{ employee.join_date }}</td>
                               </tr>



                               </tbody>
                           </table>
                           <div class="card-footer clearfix">
                                <div class="float-left">
                                    <div class="btn-toolbar">
                                        <div class="timeline-footer">
                                                <a  class="btn  btn-success btn-sm" href="{% url 'dashboard:employee-edit' pk=employee.pk %}"> <i class="fas fa-edit"></i> O‘zgartirish</a>
                                                <a  class="btn btn-danger btn-sm" href="{% url 'dashboard:employee-delete' pk=employee.pk %}"><i class="fas fa-trash"></i> O‘chirish</a>
                                        </div>
                                    </div>
                                </div>
                           </div>
                       </div>
             </div>
         </div>
     </div>
</div>
{% endblock %}

src/templates/dashboard/company/employee/form.html
{% extends "dashboard/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block title %}
  {% if employee.pk %}
    Hodim ma'lumotlari
  {% else %}
    Yangi hodim qo‘shish
  {% endif %}
{% endblock %}
{% block head_title %}
    {% if employee.pk %}
        Hodim ma'lumotlari
    {% else %}
        Yangi hodim qo‘shish
    {% endif %}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <form class="form" method="post" id="form-profession" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {% bootstrap_form_errors form layout='inline' %}

                <div class="card-body">
                    <div class="form-row">

                        <div class="form-group col-md-4">
                            {% bootstrap_field form.firstname %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.lastname %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.middlename %}
                        </div>

                        <div class="form-group col-md-4">
                            {% bootstrap_field form.email %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.phone_number %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.birthday %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.gender %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.pass_serial %}
                        </div>
                        <div class="form-group col-md-4">
                            <dif class="form-group">
                            <label for="position">Lavozim</label>
                            <select class="form-control select2"  name="position" title required id="position">
                                <option value selected>--------------</option>
                                 {% for data in position %}
                                <option value="{{data.id}}">{{data}}</option>
                                 {% endfor %}
                             </select>
                            </dif>
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.join_date %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.status %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.region %}
                        </div>

                        <div class="form-group col-md-4">
                            {% bootstrap_field form.district %}
                        </div>
                        <div class="form-group col-md-4">
                            {% bootstrap_field form.is_student %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="card-action right-align">
                            {% if employee.pk %}
                              <button type="submit" class="btn btn-block btn-success btn-sm">
                                <i class="fas fa-edit"></i> Saqlash
                              </button>
                            {% else %}
                              <button type="submit" class="btn btn-primary">
                                <i class="fas fa-plus-circle"></i>Qo‘shish
                              </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/templates/dashboard/company/employee/list.html
{% extends "dashboard/base.html" %}
{% load dashboard_utils %}
{% block title %}
    Hodimlar {{ block.super }}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Hodimlar</h3>
                <div class="card-tools">
                <a type="button" href="{% url 'dashboard:employee-add' %}" class="btn btn-block btn-primary">Qo‘shish<i class="fas fa-plus"></i></a>
              </div>

              </div>
                {% if employees %}
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">

                <table class="table table-hover text-nowrap">
                   <thead>
                      <tr>
                        <th>id</th>
                        <th>Familiya, Ism </th>
                        <th>Lavozim </th>
                        <th>Status </th>
                        <th>Actions </th>
                      </tr>
                    </thead>
                  <tbody>
                  {% for data in employees %}
                    <tr>
                      <td>{{ data.id }}</td>
                      <td><a href="{% url 'dashboard:employee-details' pk=data.id %}">{{ data.full_name }}</a></td>
                      {% if data.position_name is None %}
                      <td><i class="fa fa-minus"></i></td>
                      {% else%}
                      <td>  {{ data.position_name }}  </td>
                      {% endif %}
                      {% if data.status == 1 %}
                      <td><i class="btn btn-warning btn-sm">Faol emas</i></td>
                      {% elif data.status == 2 %}
                      <td><i class="btn btn-success btn-sm">Faol</i></td>
                      {% elif data.status == 3 %}
                      <td><i class="btn btn-success btn-sm">Mavjud emas</i></td>
                      {% else %}
                      <td><i class="btn btn-danger btn-sm">Yangi qo`shilmoqchi</i></td>
                      {% endif %}
                      <td>
                          <a data-toggle="tooltip" data-placement="top" title="edit" href="{% url 'dashboard:employee-edit' pk=data.id %}" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></a>
                          <a data-toggle="tooltip" data-placement="top" title="view detail" href="{% url 'dashboard:employee-details' pk=data.id %}" class="btn btn-info btn-sm"><i class="fas fa-user"></i></a>
                          <a href="javascript:void(0)"  data-toggle="modal"  data-placement="top" title="Delete" class="btn btn-danger btn-sm" data-url="{% url 'dashboard:employee-delete' pk=data.id %}" data-target="#deleteItemModal" data-message="{{ data.full_name }} ismli xodimni o'chirishni tasdiqlaysizmi?"><i class="fa fa-trash-alt"></i></a>                      </td>

                    </tr>
                  {% endfor %}

                  </tbody>
                </table>
                  {% paginate list %}

              </div>
              <!-- /.card-body -->
                <div class="card-footer clearfix">
                {% paginate list %}
              </div>
                {% endif %}
            </div>
            <!-- /.card -->

          </div>
</div>
{% endblock %}