src/crm/dashboard/company/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("profile/", views.company_profile, name="company-profile"),
    path("edit/", views.company_edit, name="company-edit"),
    path("positions/", views.position_list, name="position-list"),
    path('positions/<int:pk>/info/', views.position_details, name='position-details'),
    path('positions/<int:pk>/edit/', views.position_edit, name='position-edit'),
    path('positions/<int:pk>/delete/', views.position_delete, name='position-delete'),
    path('positions/add/', views.position_create, name='position-add'),
    path("employees/", views.employee_list, name="employee-list"),
    path('employees/<int:pk>/info/', views.employee_details, name='employee-details'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee-edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee-delete'),
    path('employees/add/', views.employee_create, name='employee-add'),
]

src/crm/dashboard/education/urls.py
from django.urls import path

from . import course_views, group_views, billing_views


urlpatterns = [
    path("courses/", course_views.lists, name="course-list"),
    path('courses/<int:pk>/info/', course_views.details, name='course-details'),
    path('courses/<int:pk>/edit/', course_views.edits, name='course-edit'),
    path('courses/<int:pk>/delete/', course_views.deletes, name='course-delete'),
    path('courses/add/', course_views.creates, name='course-add'),

    path("groups/", group_views.lists, name="group-list"),
    path('groups/<int:pk>/info/', group_views.details, name='group-details'),
    path('groups/<int:pk>/info/period/', group_views.details_monitoring, name='group-details-id'),
    path('groups/<int:pk>/edit/', group_views.edits, name='group-edit'),
    path('groups/<int:pk>/delete/', group_views.deletes, name='group-delete'),
    path('groupsstudent/<int:pk>/delete/', group_views.groupstudent_delete, name='groupstudent-delete'),
    path('groups/add/', group_views.creates, name='group-add'),

    path("group/student/<int:pk>/add/", group_views.add_student_group, name="add-student-group"),
    path("payment/<int:pk>/group/", billing_views.edits, name="add-payment-group"),
    path("edit/<int:pk>/group/", billing_views.edits, name="edit-payment-group"),

    path("payment/period/group/", group_views.payment_period, name="payment-period"),
    path("payment/period/<int:pk>/group/", group_views.period_list_month, name="period-list-month"),

    path("teacher/", group_views.teachers, name="teacher"),
    path("teacher/<int:pk>/data/", group_views.teachers_data, name="teachers-data"),
]

src/crm/dashboard/monitoring/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.lists, name="monitoring"),
    # path('<int:pk>/info/', views.details, name='student-details'),
    # path('<int:pk>/edit/', views.edits, name='student-edit'),
    # path('<int:pk>/delete/', views.deletes, name='student-delete'),
    # path('add/', views.creates, name='student-add'),
    # path('qrcode/<int:pk>/generator', views.qrcode_generator, name='qrcode_generator'),
]

src/crm/dashboard/students/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.lists, name="student-list"),
    path('<int:pk>/info/', views.details, name='student-details'),
    path('<int:pk>/edit/', views.edits, name='student-edit'),
    path("student/list", views.lists2, name="student-list2"),
    path("course/<int:pk>/student", views.course_students, name="course-student-list"),
    path('<int:pk>/delete/', views.deletes, name='student-delete'),
    path('add/', views.creates, name='student-add'),
    path('qrcode/<int:pk>/generator', views.qrcode_generator, name='qrcode_generator'),

    path('student/search', views.student_search_list, name='student-list-search'),
    path('student/payment/<int:pk>/pechat/', views.pechat_student_payment, name='payment-student-pechat'),
]

src/crm/dashboard/timesheet/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("times/", views.lists, name="times-list"),
    path('times/add/', views.creates, name='times-add'),
    path('times/<int:pk>/edit/', views.edits, name='times-edit'),
    path('times/<int:pk>/delete/', views.delete, name='times-delete'),
]

src/crm/dashboard/urls.py
from . import views as core_views
from django.urls import path, include
app_name = 'dashboard'
urlpatterns = [
        path('', core_views.index, name='dashboard_index'),
        path('dashboard/', core_views.index, name='dashboard_index'),
        path('login/', core_views.login, name='login'),
        path('logout/', core_views.logout, name='logout'),
        path('company/', include('crm.dashboard.company.urls')),
        path('education/', include('crm.dashboard.education.urls')),
        path('timesheet/', include('crm.dashboard.timesheet.urls')),
        path('students/', include('crm.dashboard.students.urls')),
        path('monitoring/', include('crm.dashboard.monitoring.urls')),
]

src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from .api.v1.urls import urlpatterns as v1_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include((v1_urls, 'api-v1'), namespace='api-v1')),
    path('', include('crm.dashboard.urls')),
]

src/crm/dashboard/forms.py
from django import forms
from django.contrib.auth import forms as django_forms
from django.utils.translation import pgettext

class LoginForm(django_forms.AuthenticationForm):
    username = forms.EmailField(label=pgettext("Form field", "Email"), max_length=75)

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request=request, *args, **kwargs)
        if request:
            email = request.GET.get("email")
            if email:
                self.fields["username"].initial = email

src/crm/api/v1/education/dashboard/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from .services import dashboard_data


class DashboardView(GenericAPIView):
    permission_classes = (AllowAny,)

    def get(self, request, *args, **kwargs):
        result = dashboard_data(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/dashboard/company/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from ...base.utils import sql_paginator_items
from crm.company.models import (Position, Profile, Member)
from ..views import staff_member_required
from .forms import (PositionForm, ProfileForm, EmployeeForm, StudentForm)

from .services import (list_position, list_employee,)


@staff_member_required
def company_edit(request):
    try:
        company_model = Profile.objects.order_by('id')[0:1].get()
    except Exception:
        company_model = None

    form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=company_model
    )

    if form.is_valid():
        company_model = form.save()
        return redirect("dashboard:company-profile")


    ctx = {
        "form": form,
        "company_model": company_model,
        "section": 'company',
        "active":"4",
    }
    return TemplateResponse(request, "dashboard/company/profile/form.html", ctx)

@staff_member_required
def company_profile(request):
    pk=request.user.company_id
    try:
        company_model = get_object_or_404(Profile, pk=pk)
    except Exception:
        company_model = None

    ctx = {
        "company_model": company_model,
        "section": 'company',
        "active": "4",
    }
    return TemplateResponse(request, "dashboard/company/profile/detail.html", ctx)


@staff_member_required
def position_list(request):
    pk=request.user.company_id
    positions = list_position(request, pk)
    list = sql_paginator_items(
        positions['items'], positions['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "positions": positions['items'],
        "list": list,
        "section": 'company',
        "active": "5",
    }
    return TemplateResponse(request, "dashboard/company/position/list.html", ctx)


@staff_member_required
def position_create(request):
    pk=request.user.company_id
    company = Profile.objects.get(pk=pk)
    position = Position()
    form = PositionForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        position = form.save()
        return redirect("dashboard:position-list")
    ctx = {"position": position, "form": form, "active":"5","section":"company"}
    print(form.errors)
    return TemplateResponse(request, "dashboard/company/position/form.html", ctx)


@staff_member_required
def position_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = get_object_or_404(Position, pk=pk)
    form = PositionForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=position
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:position-list")
    elif form.errors:
        status = 400
    ctx = {"position": position, "form": form,"section":"company","active":"5"}
    template = "dashboard/company/position/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def position_details(request, pk):
    position = get_object_or_404(Position, pk=pk)
    ctx = {
        "position": position,
        "active": "5",
        "section":"company",
    }
    return TemplateResponse(request, "dashboard/company/position/detail.html", ctx)


@staff_member_required
def position_delete(request, pk):
    position = get_object_or_404(Position, pk=pk)
    position.delete()
    return redirect("dashboard:position-list")


@staff_member_required
def employee_list(request):
    pk=request.user.company_id
    employees = list_employee(request, pk)
    list = sql_paginator_items(
        employees['items'], employees['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "employees": employees['items'],
        "list": list,
        "section": 'company',
        "active": "6",
    }
    return TemplateResponse(request, "dashboard/company/employee/list.html", ctx)

@staff_member_required
def employee_create(request):
    employee = Member()
    pk = request.user.company_id
    company = Profile.objects.get(pk=pk)
    position=Position.objects.filter(company_id=pk)
    form = EmployeeForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    print(form.errors)
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    return TemplateResponse(request, "dashboard/company/employee/form.html", ctx)

@staff_member_required
def employee_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = Position.objects.filter(company_id=company_id)
    employee = get_object_or_404(Member, pk=pk)
    form = EmployeeForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=employee
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    elif form.errors:
        status = 400
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    template = "dashboard/company/employee/form.html"
    return TemplateResponse(request, template, ctx, status=status)

@staff_member_required
def employee_details(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    ctx = {
        "employee": employee,
        "active": "6",
        "section": "company",
    }
    return TemplateResponse(request, "dashboard/company/employee/detail.html", ctx)

@staff_member_required
def employee_delete(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    employee.delete()
    return redirect("dashboard:employee-list")

src/crm/dashboard/monitoring/views.py
from PIL import Image,ImageFont,ImageDraw
from django.conf import settings
import pyqrcode
import qrcode
from django.http import JsonResponse,HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from ...base.utils import sql_paginator_items
from crm.company.models import Member
from ..views import staff_member_required
from .services import monitoring



@staff_member_required
def lists(request):
    students = monitoring(request)
    list = sql_paginator_items(
        students['items'], students['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "monitoring": students['items'],
        "list": list,
        "section": 'monitoring',
    }
    return TemplateResponse(request, "dashboard/monitoring/list.html", ctx)

src/crm/dashboard/timesheet/views.py
from django.conf import settings
from django.http import JsonResponse
from crm.company.models import Member
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from ...base.utils import sql_paginator_items
from ..views import staff_member_required
from .forms import TimesForm
from ...timesheet.models import Times
from .services import list_times,list_times_delete

@staff_member_required
def lists(request):
    pk=request.user.company_id
    times = list_times(request, pk)
    list = sql_paginator_items(
        times['items'], times['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "times": times['items'],
        "list": list,
        "section": 'times',
        "active": '1'
    }
    return TemplateResponse(request, "dashboard/timesheet/times/list.html", ctx)


@staff_member_required
def creates(request):
    pk=request.user.company_id
    students=Member.objects.filter(is_student=True).filter(company_id=pk)
    form = TimesForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("dashboard:times-list")
    ctx = {"form": form, "section": 'times','students':students}
    return TemplateResponse(request, "dashboard/timesheet/times/form.html", ctx)

@staff_member_required
def edits(request, pk):
    times = get_object_or_404(Times, pk=pk)
    form = TimesForm(
        request.POST or None,
        instance=times
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:times-list")
    elif form.errors:
        status = 400
    ctx = {"times": times, "form": form, "active": "2", "section":"times"}
    template = "dashboard/timesheet/times/form.html"
    return TemplateResponse(request, template, ctx, status=status)

@staff_member_required
def delete(request, pk):
    list_times_delete(pk)
    return redirect("dashboard:times-list")
    # times = list_times(request)
    # list = sql_paginator_items(
    #     times['items'], times['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    # )
    # ctx = {
    #     "times": times['items'],
    #     "list": list,
    #     "section": 'times',
    #     "active": '1'
    # }
    # return TemplateResponse(request, "dashboard/timesheet/times/list.html", ctx)

src/crm/dashboard/views.py
from django.template.response import TemplateResponse
from django.contrib import auth, messages
from django.contrib.auth import views as django_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.admin.views.decorators import (
    staff_member_required as _staff_member_required,
)
from .services import groups_count, courses_count, students_count

from .forms import LoginForm


def staff_member_required(f):
    return _staff_member_required(f, login_url="dashboard:login")


@staff_member_required
def index(request):
    ctx = {
        'company': 1,
        'section': "home",
        'courses_count': courses_count,
        'groups_count': groups_count,
        'students_count': students_count

    }
    return TemplateResponse(request, "dashboard/index.html", ctx)


def login(request):
    if request.method == 'GET' and request.user.is_active and request.user.is_staff:
        # Already logged-in, redirect to admin index
        index_path = reverse('dashboard:dashboard_index', current_app='dashboard')
        return HttpResponseRedirect(index_path)

    kwargs = {"template_name": "dashboard/login.html", "authentication_form": LoginForm}
    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)


@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, "You have been successfully logged out.")
    return redirect('dashboard:dashboard_index', )

src/templates/dashboard/_partials/footer.html
  <footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="http://proneo.uz">ProNeo</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0
    </div>
  </footer>

src/templates/dashboard/_partials/left_menu.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'dashboard:dashboard_index'%}" class="brand-link">
      <img src="{% static 'dashboard/img/kindergarten.jpg' %}"  alt="ProNeo Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Kindergarten</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dashboard/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="Admin Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Admin Manager</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          <li class="nav-item">
            <a href="{% url 'dashboard:dashboard_index' %}" class="nav-link {% if section == 'home' %} active {% endif %}">
              <i class="fa fa-th"></i>
              <p>
                DASHBOARD
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:monitoring' %}" class="nav-link {% if section == 'monitoring' %} active {% endif %}">
              <i class="fa fa-desktop" aria-hidden="true"></i>
              <p>
                MONITORING
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:group-list' %}" class="nav-link {% if section == 'group' %} active {% endif %}">
              <i class="fa fa-users" aria-hidden="true"></i>
              <p>
                GURUHLAR
              </p>
            </a>
          </li>
<!--          <li class="nav-item">-->
<!--            <a href="{% url 'dashboard:course-list' %}" class="nav-link {% if section == 'course' %} active {% endif %}">-->
<!--              <i class="fa fa-book" aria-hidden="true"></i>-->
<!--              <p>-->
<!--                KURSLAR-->
<!--              </p>-->
<!--            </a>-->
<!--          </li>-->
          <li class="nav-item">
            <a href="{% url 'dashboard:student-list' %}" class="nav-link {% if section == 'student' %} active {% endif %}">
              <i class="fa fa-user" aria-hidden="true"></i>
              <p>
                Tarbiyalanuvchilar
              </p>
            </a>
          </li>

<!--          Boshlandi-->
          <li class="nav-item">
            <a href="{% url 'dashboard:times-list' %}" class="nav-link {% if section == 'times' %} active {% endif %}">
              <i class="fa fa-clock"></i>
              <p>
                Davomat
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:student-list2' %}" class="nav-link {% if section == 'talaba' %} active {% endif %}">
              <i class="fa fa-people-arrows"></i>
              <p>
                Kutilayotgan tarbiyalanuvchilar
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:teacher' %}" class="nav-link {% if section == 'teachers' %} active {% endif %}">
              <i class="fa fa-book" aria-hidden="true"></i>
              <p>
                Tarbiyachi ma'lumotlari
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'dashboard:payment-period' %}" class="nav-link {% if section == 'period' %} active {% endif %}">
              <i class="fa fa-money-check"></i>
              <p>
                Periodlar
              </p>
            </a>
          </li>
          <li class="nav-item has-treeview {% if section == 'company' %} menu-open {% endif %}">
            <a href="#" class="nav-link">
              <i class="fa fa-bookmark"></i>
              <p>
                Tashkilot
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'dashboard:company-profile' %}" class="nav-link {% if active == '4' %} active {% endif %}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Tashkilot</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>