src/crm/dashboard/company/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("profile/", views.company_profile, name="company-profile"),
    path("edit/", views.company_edit, name="company-edit"),
    path("positions/", views.position_list, name="position-list"),
    path('positions/<int:pk>/info/', views.position_details, name='position-details'),
    path('positions/<int:pk>/edit/', views.position_edit, name='position-edit'),
    path('positions/<int:pk>/delete/', views.position_delete, name='position-delete'),
    path('positions/add/', views.position_create, name='position-add'),
    path("employees/", views.employee_list, name="employee-list"),
    path('employees/<int:pk>/info/', views.employee_details, name='employee-details'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee-edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee-delete'),
    path('employees/add/', views.employee_create, name='employee-add'),
]

src/crm/dashboard/education/urls.py
from django.urls import path

from . import course_views, group_views, billing_views


urlpatterns = [
    path("courses/", course_views.lists, name="course-list"),
    path('courses/<int:pk>/info/', course_views.details, name='course-details'),
    path('courses/<int:pk>/edit/', course_views.edits, name='course-edit'),
    path('courses/<int:pk>/delete/', course_views.deletes, name='course-delete'),
    path('courses/add/', course_views.creates, name='course-add'),

    path("groups/", group_views.lists, name="group-list"),
    path('groups/<int:pk>/info/', group_views.details, name='group-details'),
    path('groups/<int:pk>/info/period/', group_views.details_monitoring, name='group-details-id'),
    path('groups/<int:pk>/edit/', group_views.edits, name='group-edit'),
    path('groups/<int:pk>/delete/', group_views.deletes, name='group-delete'),
    path('groupsstudent/<int:pk>/delete/', group_views.groupstudent_delete, name='groupstudent-delete'),
    path('groups/add/', group_views.creates, name='group-add'),

    path("group/student/<int:pk>/add/", group_views.add_student_group, name="add-student-group"),
    path("payment/<int:pk>/group/", billing_views.edits, name="add-payment-group"),
    path("edit/<int:pk>/group/", billing_views.edits, name="edit-payment-group"),

    path("payment/period/group/", group_views.payment_period, name="payment-period"),
    path("payment/period/<int:pk>/group/", group_views.period_list_month, name="period-list-month"),

    path("teacher/", group_views.teachers, name="teacher"),
    path("teacher/<int:pk>/data/", group_views.teachers_data, name="teachers-data"),
]

src/crm/dashboard/students/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.lists, name="student-list"),
    path('<int:pk>/info/', views.details, name='student-details'),
    path('<int:pk>/edit/', views.edits, name='student-edit'),
    path("student/list", views.lists2, name="student-list2"),
    path("course/<int:pk>/student", views.course_students, name="course-student-list"),
    path('<int:pk>/delete/', views.deletes, name='student-delete'),
    path('add/', views.creates, name='student-add'),
    path('qrcode/<int:pk>/generator', views.qrcode_generator, name='qrcode_generator'),

    path('student/search', views.student_search_list, name='student-list-search'),
    path('student/payment/<int:pk>/pechat/', views.pechat_student_payment, name='payment-student-pechat'),
]

src/crm/dashboard/urls.py
from . import views as core_views
from django.urls import path, include
app_name = 'dashboard'
urlpatterns = [
        path('', core_views.index, name='dashboard_index'),
        path('dashboard/', core_views.index, name='dashboard_index'),
        path('login/', core_views.login, name='login'),
        path('logout/', core_views.logout, name='logout'),
        path('company/', include('crm.dashboard.company.urls')),
        path('education/', include('crm.dashboard.education.urls')),
        path('timesheet/', include('crm.dashboard.timesheet.urls')),
        path('students/', include('crm.dashboard.students.urls')),
        path('monitoring/', include('crm.dashboard.monitoring.urls')),
]

src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from .api.v1.urls import urlpatterns as v1_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include((v1_urls, 'api-v1'), namespace='api-v1')),
    path('', include('crm.dashboard.urls')),
]

src/crm/dashboard/forms.py
from django import forms
from django.contrib.auth import forms as django_forms
from django.utils.translation import pgettext

class LoginForm(django_forms.AuthenticationForm):
    username = forms.EmailField(label=pgettext("Form field", "Email"), max_length=75)

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request=request, *args, **kwargs)
        if request:
            email = request.GET.get("email")
            if email:
                self.fields["username"].initial = email

src/crm/dashboard/timesheet/forms.py
from django import forms
from crm.timesheet.models import Times
from ..widgets import DatePicker, TimePicker

class TimesForm(forms.ModelForm):
    time_date = forms.DateField(
        help_text="Markazga kelgan kun",
        required=True,
        label="Kun",
        widget=DatePicker,
    )

    in_time = forms.TimeField(
        help_text="Kelgan soati",
        required=True,
        label="Kelgan vaqt",
        widget=TimePicker,
    )

    out_time = forms.TimeField(
        help_text="Ketgan soati",
        required=True,
        label="Ketgan vaqt",
        widget=TimePicker,
    )


    class Meta:
        model = Times
        fields = '__all__'
        labels = {
            "member": "Shaxs",
            "time_date": "Kun",
            "in_time": "Kelgan vaqt",
            "out_time": "Ketgan vaqt",
        }

src/crm/api/v1/education/dashboard/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from .services import dashboard_data


class DashboardView(GenericAPIView):
    permission_classes = (AllowAny,)

    def get(self, request, *args, **kwargs):
        result = dashboard_data(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/dashboard/company/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from ...base.utils import sql_paginator_items
from crm.company.models import (Position, Profile, Member)
from ..views import staff_member_required
from .forms import (PositionForm, ProfileForm, EmployeeForm, StudentForm)

from .services import (list_position, list_employee,)


@staff_member_required
def company_edit(request):
    try:
        company_model = Profile.objects.order_by('id')[0:1].get()
    except Exception:
        company_model = None

    form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=company_model
    )

    if form.is_valid():
        company_model = form.save()
        return redirect("dashboard:company-profile")


    ctx = {
        "form": form,
        "company_model": company_model,
        "section": 'company',
        "active":"4",
    }
    return TemplateResponse(request, "dashboard/company/profile/form.html", ctx)

@staff_member_required
def company_profile(request):
    pk=request.user.company_id
    try:
        company_model = get_object_or_404(Profile, pk=pk)
    except Exception:
        company_model = None

    ctx = {
        "company_model": company_model,
        "section": 'company',
        "active": "4",
    }
    return TemplateResponse(request, "dashboard/company/profile/detail.html", ctx)


@staff_member_required
def position_list(request):
    pk=request.user.company_id
    positions = list_position(request, pk)
    list = sql_paginator_items(
        positions['items'], positions['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "positions": positions['items'],
        "list": list,
        "section": 'company',
        "active": "5",
    }
    return TemplateResponse(request, "dashboard/company/position/list.html", ctx)


@staff_member_required
def position_create(request):
    pk=request.user.company_id
    company = Profile.objects.get(pk=pk)
    position = Position()
    form = PositionForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        position = form.save()
        return redirect("dashboard:position-list")
    ctx = {"position": position, "form": form, "active":"5","section":"company"}
    print(form.errors)
    return TemplateResponse(request, "dashboard/company/position/form.html", ctx)


@staff_member_required
def position_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = get_object_or_404(Position, pk=pk)
    form = PositionForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=position
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:position-list")
    elif form.errors:
        status = 400
    ctx = {"position": position, "form": form,"section":"company","active":"5"}
    template = "dashboard/company/position/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def position_details(request, pk):
    position = get_object_or_404(Position, pk=pk)
    ctx = {
        "position": position,
        "active": "5",
        "section":"company",
    }
    return TemplateResponse(request, "dashboard/company/position/detail.html", ctx)


@staff_member_required
def position_delete(request, pk):
    position = get_object_or_404(Position, pk=pk)
    position.delete()
    return redirect("dashboard:position-list")


@staff_member_required
def employee_list(request):
    pk=request.user.company_id
    employees = list_employee(request, pk)
    list = sql_paginator_items(
        employees['items'], employees['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )

    ctx = {
        "employees": employees['items'],
        "list": list,
        "section": 'company',
        "active": "6",
    }
    return TemplateResponse(request, "dashboard/company/employee/list.html", ctx)

@staff_member_required
def employee_create(request):
    employee = Member()
    pk = request.user.company_id
    company = Profile.objects.get(pk=pk)
    position=Position.objects.filter(company_id=pk)
    form = EmployeeForm(request.POST or None, request.FILES or None,{'company':company})
    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    print(form.errors)
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    return TemplateResponse(request, "dashboard/company/employee/form.html", ctx)

@staff_member_required
def employee_edit(request, pk):
    company_id = request.user.company_id
    company = Profile.objects.get(pk=company_id)
    position = Position.objects.filter(company_id=company_id)
    employee = get_object_or_404(Member, pk=pk)
    form = EmployeeForm(
        request.POST or None,
        request.FILES or None,
        {'company': company},
        instance=employee
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:employee-list")
    elif form.errors:
        status = 400
    ctx = {"employee": employee, "form": form,"active":"6","section":"company",'position':position}
    template = "dashboard/company/employee/form.html"
    return TemplateResponse(request, template, ctx, status=status)

@staff_member_required
def employee_details(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    ctx = {
        "employee": employee,
        "active": "6",
        "section": "company",
    }
    return TemplateResponse(request, "dashboard/company/employee/detail.html", ctx)

@staff_member_required
def employee_delete(request, pk):
    employee = get_object_or_404(Member, pk=pk)
    employee.delete()
    return redirect("dashboard:employee-list")

src/crm/dashboard/monitoring/views.py
from PIL import Image,ImageFont,ImageDraw
from django.conf import settings
import pyqrcode
import qrcode
from django.http import JsonResponse,HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from ...base.utils import sql_paginator_items
from crm.company.models import Member
from ..views import staff_member_required
from .services import monitoring



@staff_member_required
def lists(request):
    students = monitoring(request)
    list = sql_paginator_items(
        students['items'], students['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "monitoring": students['items'],
        "list": list,
        "section": 'monitoring',
    }
    return TemplateResponse(request, "dashboard/monitoring/list.html", ctx)

src/crm/dashboard/timesheet/views.py
from django.conf import settings
from django.http import JsonResponse
from crm.company.models import Member
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from ...base.utils import sql_paginator_items
from ..views import staff_member_required
from .forms import TimesForm
from ...timesheet.models import Times
from .services import list_times,list_times_delete

@staff_member_required
def lists(request):
    pk=request.user.company_id
    times = list_times(request, pk)
    list = sql_paginator_items(
        times['items'], times['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "times": times['items'],
        "list": list,
        "section": 'times',
        "active": '1'
    }
    return TemplateResponse(request, "dashboard/timesheet/times/list.html", ctx)


@staff_member_required
def creates(request):
    pk=request.user.company_id
    students=Member.objects.filter(is_student=True).filter(company_id=pk)
    form = TimesForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("dashboard:times-list")
    ctx = {"form": form, "section": 'times','students':students}
    return TemplateResponse(request, "dashboard/timesheet/times/form.html", ctx)

@staff_member_required
def edits(request, pk):
    times = get_object_or_404(Times, pk=pk)
    form = TimesForm(
        request.POST or None,
        instance=times
    )
    status = 200

    if form.is_valid():
        form.save()
        return redirect("dashboard:times-list")
    elif form.errors:
        status = 400
    ctx = {"times": times, "form": form, "active": "2", "section":"times"}
    template = "dashboard/timesheet/times/form.html"
    return TemplateResponse(request, template, ctx, status=status)

@staff_member_required
def delete(request, pk):
    list_times_delete(pk)
    return redirect("dashboard:times-list")
    # times = list_times(request)
    # list = sql_paginator_items(
    #     times['items'], times['count'], settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    # )
    # ctx = {
    #     "times": times['items'],
    #     "list": list,
    #     "section": 'times',
    #     "active": '1'
    # }
    # return TemplateResponse(request, "dashboard/timesheet/times/list.html", ctx)

src/crm/dashboard/views.py
from django.template.response import TemplateResponse
from django.contrib import auth, messages
from django.contrib.auth import views as django_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.admin.views.decorators import (
    staff_member_required as _staff_member_required,
)
from .services import groups_count, courses_count, students_count

from .forms import LoginForm


def staff_member_required(f):
    return _staff_member_required(f, login_url="dashboard:login")


@staff_member_required
def index(request):
    ctx = {
        'company': 1,
        'section': "home",
        'courses_count': courses_count,
        'groups_count': groups_count,
        'students_count': students_count

    }
    return TemplateResponse(request, "dashboard/index.html", ctx)


def login(request):
    if request.method == 'GET' and request.user.is_active and request.user.is_staff:
        # Already logged-in, redirect to admin index
        index_path = reverse('dashboard:dashboard_index', current_app='dashboard')
        return HttpResponseRedirect(index_path)

    kwargs = {"template_name": "dashboard/login.html", "authentication_form": LoginForm}
    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)


@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, "You have been successfully logged out.")
    return redirect('dashboard:dashboard_index', )

src/templates/dashboard/qrcode/detail.html
{% extends "dashboard/base.html" %}
{% load dashboard_utils %}
{% block title %}
  Talaba - {{ student.firstname }} - {{ block.super }}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block head_title %}Talaba - {{ student.firstname }}{% endblock %}
{% block content %}
<h4>{{data}}</h4>



<div class="row">
    <div class="col-md-2">
        <a href="{% url 'dashboard:student-list' %}" class="fc-prev-button btn btn-primary"> Talabalar</a>
    </div>
</div>
<div class="row">
     <div class="col-md-12">
         <div class="card">
             <div class="card-body p-0">

                  <div class="responsive-table-plugin">
                           <table class="table table-striped mb-0">
                               <tbody>
                               <tr>
                                   <th>ID</th>
                                   <td>{{ student.id }}</td>
                               </tr>
                               <tr>
                                   <th>Ism</th>
                                   <td>{{ student.firstname }}</td>
                               </tr>
                               <tr>
                                   <th>Familiya</th>
                                   <td>{{ student.lastname }}</td>
                               </tr>
                               <tr>
                                   <th>Otasini ismi</th>
                                   <td>{{ student.middlename }}</td>
                               </tr>
                               <tr>
                                   <th>Jinsi</th>
                                   <td>{{ student.gender }}</td>
                               </tr>
                               <tr>
                                   <th>Passport</th>
                                   <td>{{ student.pass_serial }}</td>
                               </tr>
                               <tr>
                                   <th>Tug‘ilgan kun</th>
                                   <td>{{ student.birthday }}</td>
                               </tr>
                               <tr>
                                   <th>Viloyat/shahar</th>
                                   <td>{{ student.region }}</td>
                               </tr>
                               <tr>
                                   <th>Tuman</th>
                                   <td>{{ student.district }}</td>
                               </tr>
                               <tr>
                                   <th>Manzil</th>
                                   <td>{{ student.address }}</td>
                               </tr>
                               <tr>
                                   <th>Lavozim</th>
                                   <td>{{ student.position }}</td>
                               </tr>
                               <tr>
                                   <th>Telefon raqam</th>
                                   <td>{{ student.phone_number }}</td>
                               </tr>
                               <tr>
                                   <th>Email</th>
                                   <td>{{ student.email }}</td>
                               </tr>
                               <tr>
                                   <th>Ishga kelgan vaqt</th>
                                   <td>{{ student.join_date }}</td>
                               </tr>



                               </tbody>
                           </table>
                           <div class="card-footer clearfix">
                                <div class="float-left">
                                    <div class="btn-toolbar">
                                        <div class="timeline-footer">
                                                <a class="btn  btn-success btn-sm" href="{% url 'dashboard:student-edit' pk=student.pk %}"> <i class="fas fa-edit"></i> O‘zgartirish</a>
                                                <a class="btn btn-danger btn-sm" data-href="{% url 'dashboard:student-delete' pk=student.pk %}"><i class="fas fa-trash"></i> O‘chirish</a>
                                                <a class="btn btn-warning btn-sm"href="{% url 'dashboard:add-payment-group' pk=student.pk %}"><i class="fas fa-money-bill-alt"></i>To'lov</a>
                                        </div>
                                    </div>
                                </div>
                           </div>
                       </div>
             </div>
         </div>
     </div>
</div>
{% if groups %}
<div class="row">
    <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Talaba tahsil oladigan guruhlar</h3>
                <div class="card-tools">
              </div>

              </div>

              <!-- /.card-header -->
              <div class="card-body p-0">

                <table class="table">
                   <thead>
                      <tr>
                        <th>id</th>
                        <th>Nomi</th>
                        <th>Dars boshlangan sana</th>
                        <th>Dars tamomlanadigan sana</th>
                        <th>Dars boshlandaigan vaqt</th>
                        <th>Dars tamomlanadigan vaqt</th>
                      </tr>
                    </thead>
                  <tbody>
                  {% for data in groups %}
                    <tr>
                      <td>{{ data.group_id }}</td>
                      <td>{{ data.name }}</td>
                      <td>{{ data.start_date }}</td>
                      <td>{{ data.end_date }}</td>
                      <td>{{ data.start_time }}</td>
                      <td>{{ data.end_time }}</td>


                    </tr>
                  {% endfor %}

                  </tbody>
                </table>
                  {% paginate list %}

              </div>
              <!-- /.card-body -->
                <div class="card-footer clearfix">
                {% paginate list %}
              </div>

            </div>
            <!-- /.card -->

          </div>
</div>
{% endif %}
{% if payments %}
<div class="row">
    <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Kurs uchun to'lovlar tarixi</h3>
                <div class="card-tools">
              </div>

              </div>

              <!-- /.card-header -->
              <div class="card-body p-0">

                <table class="table">
                   <thead>
                      <tr>
                        <th>id</th>
                        <th>To'lov oyining boshi</th>
                        <th>To'lov oyining oxiri</th>
                        <th>To'lov miqdori</th>
                        <th>To'lov qilingan sana</th>
                        <th>To'lov qilingan guruh</th>
                      </tr>
                    </thead>
                  <tbody>
                  {% for data in payments %}
                    <tr>
                      <td>{{ data.id }}</td>
                      <td>{{ data.start_date }}</td>
                      <td>{{ data.end_date }}</td>
                      <td>{{ data.amount }}</td>
                      <td>{{ data.payment_date }}</td>
                      <td>{{ data.name }}</td>


                    </tr>
                  {% endfor %}

                  </tbody>
                </table>
                  {% paginate list %}

              </div>
              <!-- /.card-body -->
                <div class="card-footer clearfix">
                {% paginate list %}
              </div>

            </div>
            <!-- /.card -->

          </div>
</div>
{% endif %}

{% endblock %}

src/templates/dashboard/qrcode/form.html
{% extends "dashboard/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block title %}
  {% if student.pk %}
    Talaba ma'lumotlari
  {% else %}
    Talaba malumotlarini chiqarish
  {% endif %}
{% endblock %}
{% block head_title %}
    {% if student.pk %}
        Talaba ma'lumotlari
    {% else %}
        Yangi talaba qo‘shish
    {% endif %}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <form class="form" method="post" id="form-profession" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {% bootstrap_form_errors form layout='inline' %}

                <div class="card-body">
                    <div class="form-row">

                        <div class="form-group col-md-4">
                            {% bootstrap_field form.img %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="card-action right-align">
                            {% if student.pk %}
                              <button type="submit" class="btn btn-block btn-success btn-sm">
                                <i class="far fa-save"></i> Saqlash
                              </button>
                            {% else %}
                              <button type="submit" class="btn btn-primary">
                                <i class="fas fa-plus-circle"></i>Yuborish
                              </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}