src/crm/api/v1/education/urls.py
from django.urls import path

from .group_payment.views import GrPaymentView
from .group_period.views import GrPeriodView
from .qrcode_api.views import QrCodeView
from .views import GroupPeriodView
from .course.views import CourseView
from .schedule.views import ScheduleView
from .group.views import GroupView
from .group_student.views import GrStudentView
from .monitoring.views import MonitoringView
from .dashboard.views import DashboardView


urlpatterns = [
    path('period/<int:group>/list/', GroupPeriodView.as_view(), name='education_period_group_list'),
    path("course/", CourseView.as_view(), name="course_list"),
    path("course/<int:pk>/", CourseView.as_view(), name="course_one"),
    path("schedule/", ScheduleView.as_view(), name="schedule_list"),
    path("schedule/<int:pk>/", ScheduleView.as_view(), name="schedule_one"),
    path("group/", GroupView.as_view(), name="group_list"),
    path("group/<int:pk>/", GroupView.as_view(), name="group_one"),
    path("grstudent/", GrStudentView.as_view(), name="grstudent_list"),
    path("grstudent/<int:pk>/", GrStudentView.as_view(), name="grstudent_one"),
    path("studenttogroup/<int:student_id>/", GrStudentView.as_view(), name="group_using_student"),
    path("grouptostudent/<int:group_id>/", GrStudentView.as_view(), name="student_using_group"),
    path("grpayment/s/<int:gr_id>/", GrPaymentView.as_view(), name="grpayment_list-with-gr_id"),
    path("grpayment/", GrPaymentView.as_view(), name="grpayment_list"),
    path("grpayment/<int:pk>/", GrPaymentView.as_view(), name="grpayment_one"),
    path("grpayment/p/<int:period_id>/", GrPaymentView.as_view(), name="grpayment_one"),
    path("grtopayment/<int:st_id>/", GrPaymentView.as_view(), name="payment_using_student"),
    path("grperiod/", GrPeriodView.as_view(), name="grperiod_list"),
    path("grperiod/<int:pk>/", GrPeriodView.as_view(), name="grperiod_one"),
    path("mperiod/<int:m_id>/", GrPeriodView.as_view(), name="grperiod_one"),
    path("monitoring/", MonitoringView.as_view(), name="monitoring"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("qrcode/", QrCodeView.as_view(), name="qrcode")

]

src/crm/dashboard/education/urls.py
from django.urls import path

from . import course_views, group_views, billing_views


urlpatterns = [
    path("courses/", course_views.lists, name="course-list"),
    path('courses/<int:pk>/info/', course_views.details, name='course-details'),
    path('courses/<int:pk>/edit/', course_views.edits, name='course-edit'),
    path('courses/<int:pk>/delete/', course_views.deletes, name='course-delete'),
    path('courses/add/', course_views.creates, name='course-add'),

    path("groups/", group_views.lists, name="group-list"),
    path('groups/<int:pk>/info/', group_views.details, name='group-details'),
    path('groups/<int:pk>/info/period/', group_views.details_monitoring, name='group-details-id'),
    path('groups/<int:pk>/edit/', group_views.edits, name='group-edit'),
    path('groups/<int:pk>/delete/', group_views.deletes, name='group-delete'),
    path('groupsstudent/<int:pk>/delete/', group_views.groupstudent_delete, name='groupstudent-delete'),
    path('groups/add/', group_views.creates, name='group-add'),

    path("group/student/<int:pk>/add/", group_views.add_student_group, name="add-student-group"),
    path("payment/<int:pk>/group/", billing_views.edits, name="add-payment-group"),
    path("edit/<int:pk>/group/", billing_views.edits, name="edit-payment-group"),

    path("payment/period/group/", group_views.payment_period, name="payment-period"),
    path("payment/period/<int:pk>/group/", group_views.period_list_month, name="period-list-month"),

    path("teacher/", group_views.teachers, name="teacher"),
    path("teacher/<int:pk>/data/", group_views.teachers_data, name="teachers-data"),
]

src/crm/dashboard/urls.py
from . import views as core_views
from django.urls import path, include
app_name = 'dashboard'
urlpatterns = [
        path('', core_views.index, name='dashboard_index'),
        path('dashboard/', core_views.index, name='dashboard_index'),
        path('login/', core_views.login, name='login'),
        path('logout/', core_views.logout, name='logout'),
        path('company/', include('crm.dashboard.company.urls')),
        path('education/', include('crm.dashboard.education.urls')),
        path('timesheet/', include('crm.dashboard.timesheet.urls')),
        path('students/', include('crm.dashboard.students.urls')),
        path('monitoring/', include('crm.dashboard.monitoring.urls')),
]

src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from .api.v1.urls import urlpatterns as v1_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include((v1_urls, 'api-v1'), namespace='api-v1')),
    path('', include('crm.dashboard.urls')),
]

src/crm/api/v1/education/course/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound

from crm.education.models import Course
from .services import list_courses, one_course
from .serializers import CourseSerializer


class CourseView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CourseSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Course.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found course')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_course(request, kwargs['pk'])
        else:
            result = list_courses(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_course(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        course = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=course, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_course(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        course = self.get_object(*args, **kwargs)
        course.active_status = 3
        course.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/education/dashboard/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from .services import dashboard_data


class DashboardView(GenericAPIView):
    permission_classes = (AllowAny,)

    def get(self, request, *args, **kwargs):
        result = dashboard_data(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/api/v1/education/group/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound

from crm.education.models import Group
from .services import list_group, one_group
from .serializers import GroupSerializer


class GroupView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = GroupSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = Group.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found group')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_group(request, kwargs['pk'])
        else:
            result = list_group(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_group(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        group = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=group, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_group(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        group = self.get_object(*args, **kwargs)
        group.active_status = 3
        group.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/education/group_payment/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound

from crm.education.models import GroupPayment
from .services import one_grpayment, list_grpayment
from .serializers import GrPaymentSerializer


class GrPaymentView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = GrPaymentSerializer

    def get_object(self, *args, **kwargs):
        try:
            if "period_id" in kwargs and kwargs["period_id"]:
                product = GroupPayment.objects.get(period_id=kwargs['period_id'])
            else:
                product = GroupPayment.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found group_payment')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_grpayment(request, root_id=kwargs['pk'])
        elif "st_id" in kwargs and kwargs["st_id"]:
            result = one_grpayment(request, st_id=kwargs['st_id'])
        elif "gr_id" in kwargs and kwargs["gr_id"]:
            result = list_grpayment(request, gr_id=kwargs['gr_id'])
        else:
            result = list_grpayment(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_grpayment(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        root = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=root, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        print(data.pk)
        result = one_grpayment(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        root = self.get_object(*args, **kwargs)
        root.active_status = 3
        root.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/education/group_period/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound

from crm.education.models import GroupPeriod
from .services import one_grperiod, list_grperiod, list_month_period
from .serializers import GrPeriodSerializer


class GrPeriodView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = GrPeriodSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = GroupPeriod.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found group_period')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_grperiod(request, kwargs['pk'])
        elif "m_id" in kwargs and kwargs['m_id']:
            result = list_month_period(request, kwargs['m_id'])
        else:
            result = list_grperiod(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_grperiod(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        root = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=root, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_grperiod(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        root = self.get_object(*args, **kwargs)
        root.active_status = 3
        root.save()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/education/group_student/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import NotFound

from crm.education.models import GroupStudent
from .services import one_grstudent, list_grstudent
from .serializers import GrStudentSerializer


class GrStudentView(GenericAPIView):
    permission_classes = (AllowAny,)
    serializer_class = GrStudentSerializer

    def get_object(self, *args, **kwargs):
        try:
            product = GroupStudent.objects.get(id=kwargs['pk'])
        except Exception as e:
            raise NotFound('not found group_student')
        return product

    def get(self, request, *args, **kwargs):
        if "pk" in kwargs and kwargs['pk']:
            result = one_grstudent(request, grstudent_id=kwargs['pk'])
        elif "student_id" in kwargs and kwargs["student_id"]:
            result = one_grstudent(request, student_id=kwargs['student_id'])
        elif "group_id" in kwargs and kwargs["group_id"]:
            result = one_grstudent(request, edugroup_id=kwargs['group_id'])
        else:
            result = list_grstudent(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def post(self, request, *args, **kwargs):
        print(kwargs)
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.create(serializer.data)
        result = one_grstudent(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def put(self, request, *args, **kwargs):
        group = self.get_object(*args, **kwargs)
        serializer = self.get_serializer(data=request.data, instance=group, partial=True)
        serializer.is_valid(raise_exception=True)
        data = serializer.save()
        result = one_grstudent(request, data.pk)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

    def delete(self, request, *args, **kwargs):
        self.get_object(*args, **kwargs).delete()
        return Response(None, status=status.HTTP_204_NO_CONTENT)

src/crm/api/v1/education/monitoring/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import AllowAny
from .services import monitoring_data


class MonitoringView(GenericAPIView):
    permission_classes = (AllowAny,)

    def get(self, request, *args, **kwargs):
        result = monitoring_data(request)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/api/v1/education/qrcode_api/views.py
from datetime import datetime

from rest_framework import status
from rest_framework.response import Response
from rest_framework.generics import GenericAPIView
from .services import qr_code


class QrCodeView(GenericAPIView):
    def post(self, request, *args, **kwargs):
        date = datetime.now().strftime("%Y-%m-%d")
        result = qr_code(request, request.data["student_id"], date)
        return Response(result, status=status.HTTP_200_OK, content_type='application/json')

src/crm/education/views.py
from django.shortcuts import render

# Create your views here.

src/templates/dashboard/education/course/detail.html
{% extends "dashboard/base.html" %}
{% block title %}
  Kurs haqida ma'lumot - {{ block.super }}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block head_title %}{{root.content.title_ru}}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2">
        <a href="{% url 'dashboard:course-list' %}" class="fc-prev-button btn btn-primary"> <span class="fas fa-reply"></span>Kurslar ro'yhatiga o'tish</a>
    </div>
</div>
<div class="row">
     <div class="col-md-12">
         <div class="card">
             <div class="card-body p-0">

                  <div class="responsive-table-plugin">
                           <table class="table table-striped mb-0">
                               <tbody>
                               <tr>
                                   <th>ID</th>
                                   <td>{{ course.id }}</td>
                               </tr>
                               <tr>
                                   <th>Nomi</th>
                                   <td>{{ course.name }}</td>
                               </tr>
                               <tr>
                                   <th>Narxi</th>
                                   <td>{{ course.price }}</td>
                               </tr>

                               </tbody>
                           </table>
                           <div class="card-footer clearfix">
                                <div class="float-left">
                                    <div class="btn-toolbar">
                                        <div class="timeline-footer">
                                                <a data-toggle="tooltip" data-placement="top" title="edit" class="btn  btn-success btn-sm" href="{% url 'dashboard:course-edit' pk=course.id %}"> <i class="fas fa-edit"></i> O‘zgartirish</a>
                                                <a data-toggle="tooltip" data-placement="top" title="delete" class="btn btn-danger btn-sm" href="{% url 'dashboard:course-delete' pk=course.id %}"><i class="fas fa-trash"></i> O‘chirish</a>
                                        </div>
                                    </div>
                                </div>
                           </div>
                       </div>
             </div>
         </div>
     </div>
</div>
{% endblock %}

src/templates/dashboard/education/course/form.html
{% extends "dashboard/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block title %}
  {% if course %}
    Kurs ma'lumotlarini o'zgartirish
  {% else %}
    Yangi kurs qo'shish
  {% endif %}
{% endblock %}
{% block head_title %}
    {% if course %}
    Kurs ma'lumotlarini o'zgartirish
  {% else %}
    Yangi kurs qo'shish
  {% endif %}
{% endblock %}
{% block menu_categories_class %}menu-open{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary">
            <form class="form" method="post" id="form-profession" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {% bootstrap_form_errors form type='non_fields' %}
                <div class="card-body">
                    <div class="form-row">
                        <div class="col-md-4">
                            {% bootstrap_field form.name %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.price %}
                        </div>
                        <div class="col-md-4">
                            {% bootstrap_field form.active_status %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="card-action right-align">
                            {% if course %}
                              <button type="submit" class="btn btn-block btn-success btn-sm">
                                <i class="fas fa-edit"></i> Saqlash
                              </button>
                            {% else %}
                              <button type="submit" class="btn btn-primary">
                                <i class="fas fa-plus-circle"></i>Qo‘shish
                              </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/templates/dashboard/education/course/list.html
{% extends "dashboard/base.html" %}
{% load dashboard_utils %}
{% block title %}
    Kurslar ro‘yhati - {{ block.super }}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Kurslar ro‘yhati</h3>
                <div class="card-tools">
                <a type="button" href="{% url 'dashboard:course-add' %}" class="btn btn-block btn-primary">Qo'shish<i class="fas fa-plus"></i></a>
              </div>

              </div>
                {% if courses %}
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">

                <table class="table table-hover text-nowrap">
                   <thead>
                      <tr>
                        <th>id</th>
                        <th>Nomi </th>
                        <th>Narxi</th>
                        <th>Status</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                  <tbody>
                  {% for data in courses %}
                    <tr>
                      <td>{{ data.id }}</a></td>
                      <td><a href="{% url 'dashboard:course-details' pk=data.id %}">{{ data.name }}</a></td>
                      <td>{{ data.price }}</td>
                      {% if data.active_status == 1 %}
                      <td><i class="btn btn-warning btn-sm">Faol emas</i></td>
                      {% elif data.active_status == 2 %}
                      <td><i class="btn btn-success btn-sm">Faol</i></td>
                      {% elif data.active_status == 3 %}
                      <td><i class="btn btn-success btn-sm">Mavjud emas</i></td>
                      {% else %}
                      <td><i class="btn btn-danger btn-sm">Yangi qo`shilmoqchi</i></td>
                      {% endif %}
                      <td>
                          <a href="{% url 'dashboard:course-edit' pk=data.id %}" data-toggle="tooltip" data-placement="top" title="edit" class="btn btn-success btn-sm"><i class="fas fa-edit"></i></a>
                          <a href="{% url 'dashboard:course-details' pk=data.id %}" data-toggle="tooltip" data-placement="top" title="view detail" class="btn btn-info btn-sm"><i class="fas fa-user"></i></a>
                          <a href="javascript:void(0)"  data-toggle="modal"  data-placement="top" title="Delete" class="btn btn-danger btn-sm" data-url="{% url 'dashboard:course-delete' pk=data.id %}" data-target="#deleteItemModal" data-message="{{ data.name }} kursini o'chirishni tasdiqlaysizmi?"><i class="fa fa-trash-alt"></i></a>                        <td>

                    </tr>
                  {% endfor %}

                  </tbody>
                </table>
                  {% paginate list %}

              </div>
              <!-- /.card-body -->
                <div class="card-footer clearfix">
                {% paginate list %}
              </div>
                {% endif %}
            </div>
            <!-- /.card -->

          </div>
</div>
{% endblock %}